# Configuration file for Source Mage GNU/Linux repository mirroring;
# should be copied to ~/.sourcemage/mirror.yaml
---
root: /srv/git/smgl

projects:
  - name: Codex
    key: SMCDX
    repos:
      - grimoire: grimoire.git
      - grimoire-xorg-modular: grimoire/xorg-modular.git
      - grimoire-z-rejected: grimoire/z-rejected.git
      - grimoire-games: grimoire/games.git
      - grimoire-binary: grimoire/binary.git
      - grimoire-p4_history: grimoire/grimoire-p4_history.git

  - name: Cauldron
    key: SMCLD
    repos:
      - cauldron: cauldron.git

  - name: Tome
    key: SMTM
    repos:
      - tome-rdp: tome/rdp.git
      - tome-scrolls: tome/scrolls.git

  - name: Sorcery
    key: SMSRC
    repos:
      - sorcery: sorcery.git

  - name: Wand
    key: SMWND
    repos:
      - wand: wand.git

  - name: Miscellaneous
    key: SMMSC
    repos:
      - archspecs: misc/archspecs.git
      - bashdoc: misc/bashdoc.git
      - castfs: misc/castfs.git
      - enthrall: misc/enthrall.git
      - guru-tools: misc/guru-tools.git
      - licenses: misc/licenses.git
      - quill: misc/quill.git
      - prometheus: misc/prometheus.git

mirrors:
  - name: github
    username: magesync
    token: secret
    organization: sourcemage
    team_id: 0

  - name: bitbucket
    username: magesync
    token: secret

  - name: sourcehut
    username: magesync
    token: secret
    organization: sourcemage

  - name: codeberg
    username: magesync
    token: secret
    organization: sourcemage
